# Generated by Django 4.0.2 on 2022-02-19 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0003_alter_product_video_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='video_link',
            new_name='video',
        ),
    ]
