# Generated by Django 4.0.2 on 2022-02-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0006_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('seed', 'SEED AND PLANT'), ('fertilizers', 'FERTILIZERS'), ('traps', 'TRAPS'), ('pesticides', 'PESTICIDES')], default='green', max_length=20),
        ),
    ]
