# Generated by Django 4.0.3 on 2022-04-03 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0008_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
